spring:
#  profiles:
#    active: dev
  application:
    name: backend
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  #database 설정
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/rentmarketdb?useUnicode=true&allowPublicKeyRetrieval=true
    username: springboot
    password: p@ssw0rd
#  thymeleaf:
#    cache: false

#log 설정
#logging:
# config: classpath:logback-spring.xml
token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

